### ISSUE TITLE
Switching provider networks throws an error

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/scaffold-eth-typescript#42]
**Describe the bug**
Using metamask, if you switch networks while connected, an error is thrown. The app goes unresponsive, and a page refresh is required

**To Reproduce**
1. Use Meta Mask as a provider
2. Connect your wallet
3. Switch networks in Meta Mask

**Expected behavior**
Network switch should be handled gracefully

**Screenshots**
<img width="799" alt="image" src="https://user-images.githubusercontent.com/23554636/146710936-43347e3c-33f3-45c4-ae63-2d506af43e7c.png">

**Comment by ShravanSunder** [comment]
@grothem  i think i found a solution.  see https://github.com/scaffold-eth/scaffold-eth-typescript-challenges/commit/7d761c45eb658fcbe4c06f126bc231f15dde258e

This was also caused by issues I with the ipfs library and their dependencies.  Basically the package requires electron for some reason after v47 and this is a unresolved issue.

**Comment by ShravanSunder** [comment]
i referenced the wrong issues above, it was meant for #41

**Comment by ShravanSunder** [comment]
@grothem ethers recommends to reload the browser when changing chain id: https://github.com/ethers-io/ethers.js/issues/866

Currently we don't do that, as we can manage without any edge cases to the app.  

The only exception so far is console.logs.  so I think that we could ignore this until there are issues with the app itself.  What do you think?
